x-app:
  &app
  build:
    context: .
    args:
      RUBY_VERSION: '2.7.6'
  image: menfou:latest
  environment:
    &env
    RAILS_ENV: ${RAILS_ENV:-development}
    DOCKER: 'true'
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend:
  &backend
  <<: *app
  volumes:
    - ..:/app:cached
    - bundle:/usr/local/bundle
    - assets:/app/public/assets
    - rails_cache:/app/tmp/cache
  environment:
    &backend_environment
    <<: *env
    # ----
    # Service discovery
    # ----
    REDIS_URL: redis://redis:6379/
    # ----
    # Application configuration
    # ----
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-1}
    # -----
    # Caches
    # -----
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    # This env variable is used by some tools (e.g., RuboCop) to store caches
    XDG_DATA_HOME: /app/tmp/cache

  depends_on:
    &backend_depends_on
    redis:
      condition: service_healthy

services:
  setup:
    <<: *backend
    command: bin/setup

  rails:
    <<: *backend
    command: bundle exec rails

  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  redis:
    image: redis:6
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  bundle:
  assets:
  rails_cache:
  redis:
